services:
  phice:
    image: c4ffe14e/phice:latest
    container_name: phice
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./config.json:/src/phice/config.json:ro"
    restart: unless-stopped
